template: |
  ### Summary

  - insert summary here

  ### What's New

  $CHANGES

  ### Downloads
  - **🐧 Linux**: `password_board_linux.tar.gz`
  - **🪟 Windows**: `password_board_windows.zip`
  - **🍎 macOS**: `password_board_macos.zip`

  ### Installation Instructions

  **🐧 Linux:**
  ```bash
  tar -xzf password_board_linux.tar.gz
  cd password_board
  ./password_board
  ```

  **🪟 Windows:**
  ```cmd
  # Extract password_board_windows.zip
  # Run password_board.exe
  ```

  **🍎 macOS:**
  ```bash
  # Extract password_board_macos.zip
  # Run passboard_app.app
  ```

  [Full Changelog](https://github.com/barturba/passboard_app/blob/main/CHANGELOG.md)
